name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "765148-dd47be0e-5ec1-48e5-99af-36ce899cd79d" --integration-id "52962-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint  2ad69097-edcf-43b0-95db-ecff5d5aa45d --integration-id 52962